In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
df=pd.read_csv('crime_in_la.csv')

### DATASET INFORMATION

In [3]:
df.head()

,DR_NO,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,LOCATION,LAT,LON
0,190326475,01/03/2020,21:30,7,Wilshire,784,510,VEHICLE - STOLEN,0,0,M,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,AA,Adult Arrest,1900 S LONGWOOD AV,34.0375,-118.3506
1,200106753,08/02/2020,18:00,1,Central,182,330,BURGLARY FROM VEHICLE,1822 1402 0344,47,M,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,1000 S FLOWER ST,34.0444,-118.2628
2,200320258,04/11/2020,17:00,3,Southwest,356,480,BIKE - STOLEN,0344 1251,19,X,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,1400 W 37TH ST,34.0210,-118.3002
3,200907217,10/03/2020,20:37,9,Van Nuys,964,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,19,M,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,14000 RIVERSIDE DR,34.1576,-118.4387
4,220614831,17/08/2020,12:00,6,Hollywood,666,354,THEFT OF IDENTITY,1822 1501 0930 2004,28,M,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,1900 TRANSIENT,34.0944,-118.3277

In [4]:
df.isnull().sum()

DR_NO               0
DATE OCC            0
TIME OCC            0
AREA                0
AREA NAME           0
Rpt Dist No         0
Crm Cd              0
Crm Cd Desc         0
Mocodes             0
Vict Age            0
Vict Sex            0
Vict Descent        0
Premis Desc       575
Weapon Used Cd      0
Weapon Desc         0
Status              1
Status Desc         0
LOCATION            0
LAT                 0
LON                 0
dtype: int64

In [51]:
df.dtypes

DR_NO               int64
DATE OCC              str
TIME OCC              str
AREA                int64
AREA NAME             str
Rpt Dist No         int64
Crm Cd              int64
Crm Cd Desc           str
Mocodes               str
Vict Age            int64
Vict Sex              str
Vict Descent          str
Premis Desc           str
Weapon Used Cd    float64
Weapon Desc           str
Status                str
Status Desc           str
LOCATION              str
LAT               float64
LON               float64
dtype: object

In [53]:
df.describe()

,DR_NO,AREA,Rpt Dist No,Crm Cd,Vict Age,Weapon Used Cd,LAT,LON
count,9.630060e+05,963006.000000,963006.000000,963006.000000,963006.000000,963006.000000,963006.000000,963006.000000
mean,2.193097e+08,10.712636,1117.702063,500.660494,29.296909,453.974850,33.994096,-118.076735
std,1.271527e+07,6.102611,610.332012,206.634328,21.926341,96.518319,1.653217,5.730322
min,8.170000e+02,1.000000,101.000000,110.000000,-4.000000,101.000000,0.000000,-118.667600
25%,2.105155e+08,6.000000,615.000000,331.000000,0.000000,400.000000,34.014600,-118.430700
50%,2.207157e+08,11.000000,1141.000000,442.000000,30.000000,500.000000,34.058900,-118.322500
75%,2.308096e+08,16.000000,1617.000000,626.000000,45.000000,500.000000,34.164900,-118.273900
max,2.499187e+08,21.000000,2199.000000,956.000000,120.000000,516.000000,34.334300,0.000000

In [6]:
df[['Premis Desc']]

                                         Premis Desc
0                                             STREET
1                  BUS STOP/LAYOVER (ALSO QUERY 124)
2       MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)
3                                     CLOTHING STORE
4                                           SIDEWALK
...                                              ...
963001                                      DRIVEWAY
963002                                      BUS STOP
963003                                         HOTEL
963004                MTA - ORANGE LINE - CHATSWORTH
963005                                      SIDEWALK

[963006 rows x 1 columns]

In [7]:
df.columns

Index(['DR_NO', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME', 'Rpt Dist No',
       'Crm Cd', 'Crm Cd Desc', 'Mocodes', 'Vict Age', 'Vict Sex',
       'Vict Descent', 'Premis Desc', 'Weapon Used Cd', 'Weapon Desc',
       'Status', 'Status Desc', 'LOCATION', 'LAT', 'LON'],
      dtype='str')

In [8]:
df_copy=df.drop(['DR_NO','Status','Status Desc','LOCATION','Mocodes','Crm Cd' ,'AREA' ],axis=1)

In [9]:
df_copy.head()

,DATE OCC,TIME OCC,AREA NAME,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON
0,01/03/2020,21:30,Wilshire,784,VEHICLE - STOLEN,0,M,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506
1,08/02/2020,18:00,Central,182,BURGLARY FROM VEHICLE,47,M,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628
2,04/11/2020,17:00,Southwest,356,BIKE - STOLEN,19,X,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002
3,10/03/2020,20:37,Van Nuys,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19,M,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387
4,17/08/2020,12:00,Hollywood,666,THEFT OF IDENTITY,28,M,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277

In [10]:
df_copy['Vict Age'].isnull().sum()

np.int64(0)

### EXPLORATORY DATA ABALYSIS

In [11]:
df_copy['DATE OCC'] = pd.to_datetime(df_copy['DATE OCC'], errors='coerce')

df_copy['year'] = df_copy['DATE OCC'].dt.year
df_copy['month'] = df_copy['DATE OCC'].dt.month
df_copy['day'] = df_copy['DATE OCC'].dt.day

In [12]:
df_copy.head()

,DATE OCC,TIME OCC,AREA NAME,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON,year,month,day
0,2020-01-03,21:30,Wilshire,784,VEHICLE - STOLEN,0,M,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,2020.0,1.0,3.0
1,2020-08-02,18:00,Central,182,BURGLARY FROM VEHICLE,47,M,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,2020.0,8.0,2.0
2,2020-04-11,17:00,Southwest,356,BIKE - STOLEN,19,X,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,2020.0,4.0,11.0
3,2020-10-03,20:37,Van Nuys,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19,M,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,2020.0,10.0,3.0
4,NaT,12:00,Hollywood,666,THEFT OF IDENTITY,28,M,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,NaN,NaN,NaN

In [13]:
df_copy=df_copy.drop(['DATE OCC'],axis=1)

In [14]:
df_copy['TIME OCC'] = pd.to_datetime(df_copy['TIME OCC'], format='%H:%M', errors='coerce')
df_copy['hour'] = df_copy['TIME OCC'].dt.hour
df_copy['minute'] = df_copy['TIME OCC'].dt.minute

In [15]:
df_copy.head()

,TIME OCC,AREA NAME,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON,year,month,day,hour,minute
0,1900-01-01 21:30:00,Wilshire,784,VEHICLE - STOLEN,0,M,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,2020.0,1.0,3.0,21,30
1,1900-01-01 18:00:00,Central,182,BURGLARY FROM VEHICLE,47,M,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,2020.0,8.0,2.0,18,0
2,1900-01-01 17:00:00,Southwest,356,BIKE - STOLEN,19,X,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,2020.0,4.0,11.0,17,0
3,1900-01-01 20:37:00,Van Nuys,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19,M,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,2020.0,10.0,3.0,20,37
4,1900-01-01 12:00:00,Hollywood,666,THEFT OF IDENTITY,28,M,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,NaN,NaN,NaN,12,0

In [16]:
df_copy=df_copy.drop(['TIME OCC'],axis=1)

In [17]:
df_copy

,AREA NAME,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON,year,month,day,hour,minute
0,Wilshire,784,VEHICLE - STOLEN,0,M,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,2020.0,1.0,3.0,21,30
1,Central,182,BURGLARY FROM VEHICLE,47,M,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,2020.0,8.0,2.0,18,0
2,Southwest,356,BIKE - STOLEN,19,X,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,2020.0,4.0,11.0,17,0
3,Van Nuys,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19,M,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,2020.0,10.0,3.0,20,37
4,Hollywood,666,THEFT OF IDENTITY,28,M,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,NaN,NaN,NaN,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963001,Topanga,2103,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),44,F,O,DRIVEWAY,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.2260,-118.6214,NaN,NaN,NaN,23,30
963002,Olympic,2013,BATTERY - SIMPLE ASSAULT,80,F,O,BUS STOP,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",34.0690,-118.3054,NaN,NaN,NaN,15,10
963003,Central,101,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0,X,X,HOTEL,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0685,-118.2460,NaN,NaN,NaN,1,0
963004,Devonshire,1751,TRESPASSING,0,X,X,MTA - ORANGE LINE - CHATSWORTH,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.2500,-118.5990,NaN,NaN,NaN,7,57
963005,Southwest,358,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",70,F,W,SIDEWALK,308.0,STICK,34.0215,-118.2868,NaN,NaN,NaN,15,0

In [18]:
df_copy.isnull().sum()

AREA NAME              0
Rpt Dist No            0
Crm Cd Desc            0
Vict Age               0
Vict Sex               0
Vict Descent           0
Premis Desc          575
Weapon Used Cd         0
Weapon Desc            0
LAT                    0
LON                    0
year              567144
month             567144
day               567144
hour                   0
minute                 0
dtype: int64

In [19]:
df_copy['year'].nunique()

5

In [20]:
df_copy.shape

(963006, 16)

In [21]:
(df_copy['year'].isna().sum() / len(df)) * 100

np.float64(58.89309100877876)

In [22]:
df_copy[['year','month','day']].isnull().mean() * 100

year     58.893091
month    58.893091
day      58.893091
dtype: float64

In [23]:
for col in ['year', 'month', 'day']:
    df_copy[col] = df_copy.groupby(['AREA NAME', 'hour'])[col]\
                .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [24]:
for col in ['year', 'month', 'day']:
    df_copy[col] = df_copy[col].fillna(df_copy[col].mode()[0])

In [25]:
df_copy.isnull().sum()

AREA NAME           0
Rpt Dist No         0
Crm Cd Desc         0
Vict Age            0
Vict Sex            0
Vict Descent        0
Premis Desc       575
Weapon Used Cd      0
Weapon Desc         0
LAT                 0
LON                 0
year                0
month               0
day                 0
hour                0
minute              0
dtype: int64

In [26]:
(df_copy['Premis Desc'].isna().sum() / len(df)) * 100

np.float64(0.05970886993435139)

In [27]:
df_copy['Premis Desc'] = df_copy['Premis Desc'].fillna(df_copy['Premis Desc'].mode()[0])

In [28]:
df['Premis Desc'].value_counts().head()

Premis Desc
STREET                                          246970
SINGLE FAMILY DWELLING                          160348
MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)    116039
PARKING LOT                                      66334
OTHER BUSINESS                                   45763
Name: count, dtype: int64

In [29]:
df_copy[['Vict Age']]

        Vict Age
0              0
1             47
2             19
3             19
4             28
...          ...
963001        44
963002        80
963003         0
963004         0
963005        70

[963006 rows x 1 columns]

In [30]:

df_copy['Vict Age'] = df_copy['Vict Age'].apply(lambda x: x if x > 0 and x < 100 else np.nan)

In [31]:
df_copy['Vict Age'] = df_copy['Vict Age'].fillna(df_copy['Vict Age'].median())

In [32]:
df_copy[['Vict Sex']]

       Vict Sex
0             M
1             M
2             X
3             M
4             M
...         ...
963001        F
963002        F
963003        X
963004        X
963005        F

[963006 rows x 1 columns]

In [33]:
df_copy['Vict Sex'] = df_copy['Vict Sex'].fillna('X')

In [34]:
df_copy['Vict Sex'].unique()

<StringArray>
['M', 'X', 'F', 'H', '-']
Length: 5, dtype: str

In [35]:
df_copy['Vict Sex'] = df_copy['Vict Sex'].replace('-', np.nan)

In [36]:
df_copy['Vict Sex'] = df_copy['Vict Sex'].replace('H', 'X')

In [37]:
df_copy['Vict Sex'].unique()

<StringArray>
['M', 'X', 'F', nan]
Length: 4, dtype: str

In [38]:
df_copy['Vict Sex'] = df_copy['Vict Sex'].fillna('X')

In [39]:
df_copy['Vict Sex'].unique()

<StringArray>
['M', 'X', 'F']
Length: 3, dtype: str

### ENCODING

In [40]:
df_copy['Vict Sex'] = df_copy['Vict Sex'].map({'M': 1, 'F': 0, 'X': 2})

In [41]:
df_copy.head()

,AREA NAME,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON,year,month,day,hour,minute
0,Wilshire,784,VEHICLE - STOLEN,37.0,1,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,2020.0,1.0,3.0,21,30
1,Central,182,BURGLARY FROM VEHICLE,47.0,1,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,2020.0,8.0,2.0,18,0
2,Southwest,356,BIKE - STOLEN,19.0,2,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,2020.0,4.0,11.0,17,0
3,Van Nuys,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19.0,1,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,2020.0,10.0,3.0,20,37
4,Hollywood,666,THEFT OF IDENTITY,28.0,1,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,2022.0,1.0,3.0,12,0

In [42]:
df_copy = pd.get_dummies(df_copy, columns=['AREA NAME'], dtype=int)

In [43]:
df_copy.head()

,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Used Cd,Weapon Desc,LAT,LON,...,AREA NAME_Olympic,AREA NAME_Pacific,AREA NAME_Rampart,AREA NAME_Southeast,AREA NAME_Southwest,AREA NAME_Topanga,AREA NAME_Van Nuys,AREA NAME_West LA,AREA NAME_West Valley,AREA NAME_Wilshire
0,784,VEHICLE - STOLEN,37.0,1,O,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,...,0,0,0,0,0,0,0,0,0,1
1,182,BURGLARY FROM VEHICLE,47.0,1,O,BUS STOP/LAYOVER (ALSO QUERY 124),500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,...,0,0,0,0,0,0,0,0,0,0
2,356,BIKE - STOLEN,19.0,2,X,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,...,0,0,0,0,1,0,0,0,0,0
3,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19.0,1,O,CLOTHING STORE,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,...,0,0,0,0,0,0,1,0,0,0
4,666,THEFT OF IDENTITY,28.0,1,H,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,...,0,0,0,0,0,0,0,0,0,0

In [44]:
df_copy['Premis Desc'].nunique()

306

In [45]:

top_premis = df_copy['Premis Desc'].value_counts().nlargest(20).index

df_copy['Premis Desc'] = df_copy['Premis Desc'].apply(
    lambda x: x if x in top_premis else 'OTHER'
)

#One-copyhot encode
df_copy = pd.get_dummies(df_copy, columns=['Premis Desc'], dtype=int)

In [46]:
df_copy.head()

,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Used Cd,Weapon Desc,LAT,LON,year,...,Premis Desc_OTHER RESIDENCE,Premis Desc_PARK/PLAYGROUND,Premis Desc_PARKING LOT,Premis Desc_PARKING UNDERGROUND/BUILDING,Premis Desc_RESTAURANT/FAST FOOD,Premis Desc_SIDEWALK,Premis Desc_SINGLE FAMILY DWELLING,Premis Desc_STREET,"Premis Desc_VEHICLE, PASSENGER/TRUCK",Premis Desc_YARD (RESIDENTIAL/BUSINESS)
0,784,VEHICLE - STOLEN,37.0,1,O,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0375,-118.3506,2020.0,...,0,0,0,0,0,0,0,1,0,0
1,182,BURGLARY FROM VEHICLE,47.0,1,O,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0444,-118.2628,2020.0,...,0,0,0,0,0,0,0,0,0,0
2,356,BIKE - STOLEN,19.0,2,X,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0210,-118.3002,2020.0,...,0,0,0,0,0,0,0,0,0,0
3,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19.0,1,O,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.1576,-118.4387,2020.0,...,0,0,0,0,0,0,0,0,0,0
4,666,THEFT OF IDENTITY,28.0,1,H,500.0,UNKNOWN WEAPON/OTHER WEAPON,34.0944,-118.3277,2022.0,...,0,0,0,0,0,1,0,0,0,0

In [47]:
df_copy['Weapon Desc'].nunique()

79

In [48]:
df_copy['Crm Cd Desc'].nunique()

139

In [49]:
df_copy.drop(['Weapon Desc'], axis=1, inplace=True)

In [50]:
df_copy.head()

,Rpt Dist No,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Used Cd,LAT,LON,year,month,...,Premis Desc_OTHER RESIDENCE,Premis Desc_PARK/PLAYGROUND,Premis Desc_PARKING LOT,Premis Desc_PARKING UNDERGROUND/BUILDING,Premis Desc_RESTAURANT/FAST FOOD,Premis Desc_SIDEWALK,Premis Desc_SINGLE FAMILY DWELLING,Premis Desc_STREET,"Premis Desc_VEHICLE, PASSENGER/TRUCK",Premis Desc_YARD (RESIDENTIAL/BUSINESS)
0,784,VEHICLE - STOLEN,37.0,1,O,500.0,34.0375,-118.3506,2020.0,1.0,...,0,0,0,0,0,0,0,1,0,0
1,182,BURGLARY FROM VEHICLE,47.0,1,O,500.0,34.0444,-118.2628,2020.0,8.0,...,0,0,0,0,0,0,0,0,0,0
2,356,BIKE - STOLEN,19.0,2,X,500.0,34.0210,-118.3002,2020.0,4.0,...,0,0,0,0,0,0,0,0,0,0
3,964,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19.0,1,O,500.0,34.1576,-118.4387,2020.0,10.0,...,0,0,0,0,0,0,0,0,0,0
4,666,THEFT OF IDENTITY,28.0,1,H,500.0,34.0944,-118.3277,2022.0,1.0,...,0,0,0,0,0,1,0,0,0,0

In [64]:
df_copy['Vict Descent'].value_counts()

Vict Descent
H    289523
X    231919
W    193742
B    132945
O     75549
A     20828
K      5443
F      4338
C      4039
J      1417
V      1071
I       936
Z       506
P       265
U       207
D        84
G        69
L        69
S        54
-         2
Name: count, dtype: int64

In [67]:
import numpy as np

df_copy['Vict Descent'] = df_copy['Vict Descent'].replace('-', np.nan)

df_copy['Vict Descent'] = df_copy['Vict Descent'].fillna('X')

In [69]:
top_desc = df_copy['Vict Descent'].value_counts().nlargest(8).index

df_copy['Vict Descent'] = df_copy['Vict Descent'].apply(
    lambda x: x if x in top_desc else 'OTHER'
)

In [70]:
df_copy = pd.get_dummies(df_copy, columns=['Vict Descent'], dtype=int)

In [71]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 963006 entries, 0 to 963005
Data columns (total 62 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   Rpt Dist No                                               963006 non-null  int64
 1   Crm Cd Desc                                               963006 non-null  str
 2   Vict Age                                                  963006 non-null  float64
 3   Vict Sex                                                  963006 non-null  int64
 4   Weapon Used Cd                                            963006 non-null  float64
 5   LAT                                                       963006 non-null  float64
 6   LON                                                       963006 non-null  float64
 7   year                                                      963006 non-null  float64
 8   month                                                     963006 non-null  float64
 9   day                                                       963006 non-null  float64
 10  hour                                                      963006 non-null  int32
 11  minute                                                    963006 non-null  int32
 12  AREA NAME_77th Street                                     963006 non-null  int64
 13  AREA NAME_Central                                         963006 non-null  int64
 14  AREA NAME_Devonshire                                      963006 non-null  int64
 15  AREA NAME_Foothill                                        963006 non-null  int64
 16  AREA NAME_Harbor                                          963006 non-null  int64
 17  AREA NAME_Hollenbeck                                      963006 non-null  int64
 18  AREA NAME_Hollywood                                       963006 non-null  int64
 19  AREA NAME_Mission                                         963006 non-null  int64
 20  AREA NAME_N Hollywood                                     963006 non-null  int64
 21  AREA NAME_Newton                                          963006 non-null  int64
 22  AREA NAME_Northeast                                       963006 non-null  int64
 23  AREA NAME_Olympic                                         963006 non-null  int64
 24  AREA NAME_Pacific                                         963006 non-null  int64
 25  AREA NAME_Rampart                                         963006 non-null  int64
 26  AREA NAME_Southeast                                       963006 non-null  int64
 27  AREA NAME_Southwest                                       963006 non-null  int64
 28  AREA NAME_Topanga                                         963006 non-null  int64
 29  AREA NAME_Van Nuys                                        963006 non-null  int64
 30  AREA NAME_West LA                                         963006 non-null  int64
 31  AREA NAME_West Valley                                     963006 non-null  int64
 32  AREA NAME_Wilshire                                        963006 non-null  int64
 33  Premis Desc_ALLEY                                         963006 non-null  int64
 34  Premis Desc_CLOTHING STORE                                963006 non-null  int64
 35  Premis Desc_DEPARTMENT STORE                              963006 non-null  int64
 36  Premis Desc_DRIVEWAY                                      963006 non-null  int64
 37  Premis Desc_GARAGE/CARPORT                                963006 non-null  int64
 38  Premis Desc_GAS STATION                                   963006 non-null  int64
 39  Premis Desc_MARKET                                        963006 non-null  int64
 40  Premis Desc_MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)  963006 non-null  int64
 41  Premis Desc_OTHER                                         963006 non-null  int64
 42  Premis Desc_OTHER BUSINESS                                963006 non-null  int64
 43  Premis Desc_OTHER PREMISE                                 963006 non-null  int64
 44  Premis Desc_OTHER RESIDENCE                               963006 non-null  int64
 45  Premis Desc_PARK/PLAYGROUND                               963006 non-null  int64
 46  Premis Desc_PARKING LOT                                   963006 non-null  int64
 47  Premis Desc_PARKING UNDERGROUND/BUILDING                  963006 non-null  int64
 48  Premis Desc_RESTAURANT/FAST FOOD                          963006 non-null  int64
 49  Premis Desc_SIDEWALK                                      963006 non-null  int64
 50  Premis Desc_SINGLE FAMILY DWELLING                        963006 non-null  int64
 51  Premis Desc_STREET                                        963006 non-null  int64
 52  Premis Desc_VEHICLE, PASSENGER/TRUCK                      963006 non-null  int64
 53  Premis Desc_YARD (RESIDENTIAL/BUSINESS)                   963006 non-null  int64
 54  Vict Descent_A                                            963006 non-null  int64
 55  Vict Descent_B                                            963006 non-null  int64
 56  Vict Descent_H                                            963006 non-null  int64
 57  Vict Descent_K                                            963006 non-null  int64
 58  Vict Descent_O                                            963006 non-null  int64
 59  Vict Descent_OTHER                                        963006 non-null  int64
 60  Vict Descent_W                                            963006 non-null  int64
 61  Vict Descent_X                                            963006 non-null  int64
dtypes: float64(7), int32(2), int64(52), str(1)
memory usage: 448.2 MB

### MODEL TRAINING

In [72]:
##independent and DEpendent feature 
x= df_copy.drop(['Crm Cd Desc'], axis=1)
y= df_copy['Crm Cd Desc']

In [73]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
y= le.fit_transform(df_copy['Crm Cd Desc'])

In [74]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [75]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

model.fit(x_train, y_train)

RandomForestClassifier(max_depth=20, n_jobs=-1, random_state=42)

In [76]:
y_pred = model.predict(x_test)

In [77]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.4701716493078992
              precision    recall  f1-score   support

           0       0.91      0.02      0.04       521
           1       0.93      0.29      0.45       224
           2       0.50      0.72      0.59     10702
           3       0.00      0.00      0.00       972
           4       0.51      0.72      0.59     15014
           5       0.00      0.00      0.00        43
           6       0.58      0.32      0.42       478
           7       0.33      0.00      0.00       863
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       0.56      0.05      0.09      1609
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00        26
          14       0.83      0.16      0.28        91
          15       0.52      0.04      0.08      2864
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00        60
          18       0.00      0.00      0.00      1196
          19       0.00      0.00      0.00       420
          20       0.35      0.51      0.42     11577
          21       0.36      0.72      0.48     11864
          22       0.00      0.00      0.00       149
          23       0.00      0.00      0.00       817
          24       0.00      0.00      0.00         1
          25       1.00      0.02      0.03       119
          26       0.46      0.49      0.47       716
          27       0.32      0.14      0.20       196
          28       0.58      0.28      0.37       236
          29       1.00      0.02      0.03        61
          30       0.00      0.00      0.00       100
          31       0.00      0.00      0.00         2
          32       0.51      0.05      0.09       553
          33       0.00      0.00      0.00         8
          34       0.00      0.00      0.00        25
          35       0.00      0.00      0.00        24
          36       0.00      0.00      0.00        20
          37       0.50      0.00      0.01       325
          38       0.73      0.90      0.81      3881
          39       0.38      0.30      0.34       342
          40       0.00      0.00      0.00        45
          41       0.00      0.00      0.00        78
          42       0.00      0.00      0.00        11
          43       0.65      0.64      0.65       550
          44       0.00      0.00      0.00         5
          45       0.00      0.00      0.00         6
          47       0.00      0.00      0.00         3
          48       1.00      0.00      0.01       330
          49       0.00      0.00      0.00       676
          50       0.00      0.00      0.00         7
          51       0.00      0.00      0.00        19
          52       0.00      0.00      0.00        42
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         6
          55       0.65      0.52      0.58       789
          56       0.00      0.00      0.00        25
          57       0.29      0.01      0.02       398
          58       0.00      0.00      0.00         1
          59       0.54      0.18      0.27       306
          60       1.00      0.01      0.03        68
          61       0.00      0.00      0.00        36
          62       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         4
          66       0.72      0.56      0.63        99
          67       0.00      0.00      0.00        24
          68       0.00      0.00      0.00        18
          70       0.00      0.00      0.00         5
          71       0.83      0.02      0.04       231
          72       0.37      0.01      0.02      2550
          73       0.49      0.61      0.54      9347
          74       1.00      0.01      0.01       174
          75       0.00      0.00      0.00        43
          76       0.29      0.00      0.00      1641
          77       0.50      0.01      0.01       159
          78       0.00      0.00      0.00        15
          79       0.00      0.00      0.00         3
          80       0.00      0.00      0.00         3
          81       0.00      0.00      0.00         2
          82       0.00      0.00      0.00       142
          83       1.00      0.00      0.01       870
          84       0.37      0.01      0.01      1367
          85       0.50      0.17      0.25        36
          86       0.00      0.00      0.00        83
          87       0.00      0.00      0.00         1
          88       0.57      0.25      0.34       633
          90       1.00      0.06      0.12        31
          91       0.00      0.00      0.00        33
          92       0.00      0.00      0.00        24
          93       0.00      0.00      0.00         5
          94       0.00      0.00      0.00        65
          95       0.44      0.02      0.04       797
          96       0.00      0.00      0.00        67
          97       0.00      0.00      0.00         3
          98       0.42      0.08      0.14       193
          99       0.59      0.22      0.32      6385
         100       0.86      0.62      0.72       181
         101       0.43      0.20      0.27       222
         102       0.00      0.00      0.00       272
         103       0.00      0.00      0.00        26
         104       0.52      0.81      0.63      5321
         105       0.47      0.01      0.01      1054
         106       0.87      0.15      0.26       350
         107       1.00      0.01      0.02        80
         108       0.00      0.00      0.00        97
         109       1.00      0.01      0.01       137
         111       0.00      0.00      0.00       168
         112       0.33      0.23      0.27      6947
         113       0.50      0.00      0.01      7717
         114       0.00      0.00      0.00        17
         115       0.33      0.76      0.46     11910
         116       0.00      0.00      0.00        96
         117       0.25      0.38      0.30      9868
         118       0.00      0.00      0.00         2
         120       0.00      0.00      0.00         6
         121       0.00      0.00      0.00       794
         122       0.38      0.04      0.08      6532
         123       0.00      0.00      0.00       103
         124       0.00      0.00      0.00       186
         125       0.00      0.00      0.00         3
         126       0.00      0.00      0.00         8
         127       0.00      0.00      0.00         1
         128       0.64      0.27      0.38      3215
         129       0.00      0.00      0.00       112
         130       0.56      0.32      0.41     11550
         131       0.25      0.00      0.01      4903
         132       0.00      0.00      0.00       800
         133       0.75      0.99      0.85     21105
         134       0.60      0.02      0.04       486
         135       0.33      0.00      0.00      1264
         136       0.34      0.11      0.17      2301
         137       0.00      0.00      0.00       193
         138       0.00      0.00      0.00         8

    accuracy                           0.47    192602
   macro avg       0.27      0.11      0.11    192602
weighted avg       0.46      0.47      0.40    192602

/Users/najeebahmad/flask_project/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/najeebahmad/flask_project/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/najeebahmad/flask_project/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])